In [19]:
my_circle = Circle(5. )

In [20]:
my_circle.radius

5.0

In [21]:
my_circle.get_radius()

5.0

In [22]:
my_circle.getArea()

78.5

In [25]:
c1 = Circle(1.2)
c2 = Circle(2.0)
c1 <= c2

True

# 넘파이

In [6]:
import numpy as npa

In [7]:
a = np.array([1,2,3])

In [8]:
type(a)

numpy.ndarray

In [9]:
print(a)

[1 2 3]


In [11]:
a

array([1, 2, 3])

In [12]:
a.ndim

1

In [14]:
a.shape

(3,)

In [15]:
a.dtype

dtype('int32')

In [16]:
b = np.array([[1,2,3],[4,5,6]])

In [17]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
b.ndim

2

In [19]:
b.shape

(2, 3)

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.full((3,5),100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
np.random.random()

0.43247341602011813

In [28]:
np.random.seed(0)

In [29]:
np.random.random((3,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492]])

In [30]:
np.random.normal(0,1,(3,4))

array([[ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502]])

In [32]:
np.random.randint(0,10,(3,4))

array([[7, 2, 0, 0],
       [4, 5, 5, 6],
       [8, 4, 1, 4]])

In [33]:
a = np.arange(5,15,2)

In [34]:
a

array([ 5,  7,  9, 11, 13])

In [36]:
b = np.random.randint(1,11,size=(2,5))

In [37]:
b

array([[10,  9,  2,  2,  8],
       [10, 10,  4,  7,  8]])

In [38]:
b[1, :]

array([10, 10,  4,  7,  8])

In [40]:
b2 =b[:,2]

In [41]:
b2

array([2, 4])

In [42]:
b2[0] = 100

In [43]:
b2

array([100,   4])

In [46]:
grid = np.arange(1,10).reshape((3,3))

In [47]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
a = np.array([2,4,8])

In [49]:
m = np.arange(1,11).reshape(2,5)

In [50]:
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [51]:
m.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [52]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [54]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [55]:
m1 = np.array([[1,1],[2,2]])

In [56]:
m1

array([[1, 1],
       [2, 2]])

In [57]:
m2 = np.full((2,2),100)

In [58]:
m2

array([[100, 100],
       [100, 100]])

In [59]:
np.concatenate([m1,m2])

array([[  1,   1],
       [  2,   2],
       [100, 100],
       [100, 100]])

In [60]:
np.concatenate((m1,m2), axis=1)

array([[  1,   1, 100, 100],
       [  2,   2, 100, 100]])