# Numpy 배열 연산

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
b = np.array([5,5,5]) #np.full 함수도 사용 가능

In [4]:
a + b

array([6, 7, 8])

In [5]:
(a + 1)**2

array([ 4,  9, 16], dtype=int32)

In [6]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [10]:
np.arange(3).reshape(3,1)+np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [13]:
np.random.seed(0)

In [14]:
x = np.random.random(10)

In [15]:
x

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [16]:
sum(x)

6.157662833145425

In [17]:
np.sum(x)

6.157662833145425

In [19]:
%timeit sum(np.random.random(10000))

859 µs ± 10.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [20]:
%timeit np.sum(np.random.random(10000))

84.8 µs ± 609 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [21]:
y = np.array([[1,2],[3,4]])

In [22]:
y

array([[1, 2],
       [3, 4]])

In [23]:
np.sum(y)

10

In [25]:
np.sum(y, axis=0) #열별 합(colum sum)

array([4, 6])

In [26]:
np.sum(y, axis=1)

array([3, 7])

In [32]:
t = np.array([5,2,8,5,1], dtype = np.float64)

In [28]:
np.max(t)

8

In [30]:
np.argmax(t) #최대값의 인덱스 반환

2

In [33]:
t[0] = np.NaN #NaN == Not a Number

In [34]:
t

array([nan,  2.,  8.,  5.,  1.])

In [35]:
np.sum(t)

nan

In [37]:
np.nansum(t)

16.0

In [38]:
x = np.array([4,3,6,7,3.3])

In [40]:
z = (x - np.mean(x))/np.std(x)

In [41]:
z

array([-0.42059551, -1.05786144,  0.85393634,  1.49120227, -0.86668166])

In [42]:
z.mean()

-1.3322676295501878e-16

In [43]:
z.std()

1.0

In [44]:
X = np.random.randint(0,100,(10,2))

In [45]:
X

array([[89, 96],
       [20, 38],
       [45, 18],
       [51, 65],
       [90, 76],
       [ 7, 14],
       [34, 83],
       [95,  3],
       [35, 14],
       [86, 76]])

In [47]:
avgs = np.mean(X, axis=0)

In [48]:
avgs

array([55.2, 48.3])

In [49]:
sds = np.std(X, axis=0)

In [50]:
sds

array([30.70439708, 32.74461788])

In [51]:
Z = (X - avgs) / sds

In [52]:
Z

array([[ 1.10081953,  1.45672795],
       [-1.14641561, -0.31455551],
       [-0.33219998, -0.92534291],
       [-0.13678823,  0.51000748],
       [ 1.13338816,  0.84594055],
       [-1.56980773, -1.04750039],
       [-0.69045485,  1.05971614],
       [ 1.29623128, -1.38343346],
       [-0.65788623, -1.04750039],
       [ 1.00311366,  0.84594055]])

In [53]:
x = np.arange(7)

In [54]:
x

array([0, 1, 2, 3, 4, 5, 6])

In [55]:
x < 3

array([ True,  True,  True, False, False, False, False])

In [56]:
np.where(x < 3, 1, 0)

array([1, 1, 1, 0, 0, 0, 0])

In [57]:
x[x<3]

array([0, 1, 2])

In [58]:
a = np.array([[0,1],[2,3]])

In [59]:
b = np.array([[1,1],[4,0]])

In [60]:
a

array([[0, 1],
       [2, 3]])

In [61]:
b

array([[1, 1],
       [4, 0]])

In [62]:
a @ b #행렬

array([[ 4,  0],
       [14,  2]])

In [63]:
np.dot(a,b)

array([[ 4,  0],
       [14,  2]])